/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Funciones.FunctionGrafo;
import Funciones.FunctionTXT;
import Funciones.LeerArchivo;
import javax.swing.JOptionPane;
import static proyecto1.main.grafo;

/**
 *
 * @author yaxim
 */
public class AgregarRelacion extends javax.swing.JFrame {

    /**
     * Creates new form AgregarRelacion
     */
    public AgregarRelacion() {
        initComponents();
        
        InicializarComboBox();
    }
    
    LeerArchivo f = new LeerArchivo();
    FunctionTXT content = new FunctionTXT();
    FunctionGrafo fGraph = new FunctionGrafo();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AgregarUser = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        UserList2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Exit1 = new javax.swing.JButton();
        UserList1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lista de Usuarios:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        AgregarUser.setBackground(new java.awt.Color(0, 0, 153));
        AgregarUser.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        AgregarUser.setForeground(new java.awt.Color(255, 255, 255));
        AgregarUser.setText("Agregar");
        AgregarUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AgregarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarUserActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 140, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lista de Usuarios : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        UserList2.setToolTipText("");
        UserList2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UserList2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserList2ActionPerformed(evt);
            }
        });
        getContentPane().add(UserList2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 230, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Seleccione con que usuario de la lista se relacionara");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        Exit1.setBackground(new java.awt.Color(255, 255, 255));
        Exit1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Exit1.setForeground(new java.awt.Color(0, 0, 0));
        Exit1.setText("Salir");
        Exit1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit1ActionPerformed(evt);
            }
        });
        getContentPane().add(Exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 50, -1));

        UserList1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UserList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserList1MouseClicked(evt);
            }
        });
        UserList1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserList1ActionPerformed(evt);
            }
        });
        getContentPane().add(UserList1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 230, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sin título-3_page-0001.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarUserActionPerformed
        // TODO add your handling code here:

        String infoGrafo = f.leertxt("test\\proyecto.txt");
        String[] users = content.getUsuarios(infoGrafo);
        String[] relaciones = content.getRelaciones(infoGrafo);
        Object selectedItem1 = UserList1.getSelectedItem(); 
        Object selectedItem2 = UserList2.getSelectedItem(); 
        int userId1 = getUserIdByName(users, selectedItem1.toString());
        int userId2 = getUserIdByName(users, selectedItem2.toString());
        boolean valido = validarRelacion(relaciones, userId1,userId2);
       
        if(!valido){
            JOptionPane.showMessageDialog(null, "La relación ya existe\nPor favor intentelo de nuevo");
        }
        else {
            String contenidoFile = "Usuarios\n";  
            for (int i = 1; i < users.length; i++) {
                contenidoFile += users[i] + "\n";               
            }
            contenidoFile += "Relaciones\n";
            for (int j = 1; j < relaciones.length; j++) {
                contenidoFile += relaciones[j]+ "\n";      
            }
            contenidoFile += userId1 + ", " + userId2 + "\n";

            content.escribir_txt(contenidoFile);
                       
            String[] usuariosActualizados = content.getUsuarios(contenidoFile);
            String[] relacionesActualizadas = content.getRelaciones(contenidoFile);                
            grafo = fGraph.crearGrafo(usuariosActualizados, relacionesActualizadas);  
            JOptionPane.showMessageDialog(null, "Relación guardada exitosamente");
        }
    }//GEN-LAST:event_AgregarUserActionPerformed

    private void UserList2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserList2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserList2ActionPerformed

    private void Exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Exit1ActionPerformed

    private void UserList1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserList1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserList1ActionPerformed

    private void UserList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserList1MouseClicked
        // TODO add your handling code here:
        UserList2.removeAll();
        String infoGrafo = f.leertxt("test\\proyecto.txt");
        String[] users = content.getUsuarios(infoGrafo);
        Object selectedItem = UserList1.getSelectedItem();
        for (int i = 1; i < users.length; i++) {
            String[] info = users[i].trim().split(",");
            String username = info[1].trim();
            String id = info[0].trim();  
            if (!username.equalsIgnoreCase(selectedItem.toString())) {
                UserList2.addItem(username);
            }
        }
    }//GEN-LAST:event_UserList1MouseClicked

    private void InicializarComboBox() {
        
        String infoGrafo = f.leertxt("test\\proyecto.txt");
        String[] users = content.getUsuarios(infoGrafo);
        //String[] relaciones = content.getRelaciones(infoGrafo);
        for (int i = 1; i < users.length; i++) {
            String[] info = users[i].trim().split(",");
            String username = info[1].trim();
            String id = info[0].trim();  
            UserList1.addItem(username);
         }
    }
    
    private int getUserIdByName(String[] users, String selectedItemName) {
        for (int i = 1; i < users.length; i++) {
            String[] info = users[i].trim().split(",");
            String username = info[1].trim();
            String id = info[0].trim();  
            if (username.equalsIgnoreCase(selectedItemName)) {
                return Integer.parseInt(id);
            }
        }
        return -1;
    }
    
    private boolean validarRelacion(String[]relaciones, int userId1, int userId2) {
        for (int j = 1; j < relaciones.length; j++) {
            String[] relationships = relaciones[j].trim().split(",");
            int id1 = Integer.parseInt(relationships[0].trim());
            int id2 = Integer.parseInt(relationships[1].trim());
            if (id1 == userId1 && id2 == userId2) {
                return false;
            }     
        }
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarRelacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarRelacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarRelacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarRelacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarRelacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarUser;
    private javax.swing.JButton Exit1;
    private javax.swing.JComboBox<String> UserList1;
    private javax.swing.JComboBox<String> UserList2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
