/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Funciones.FunctionGrafo;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import org.graphstream.graph.Graph;
import proyecto1.Grafo;
import static proyecto1.main.grafo;



/**
 *
 * @author yaxim
 */
public class Bienvenida extends javax.swing.JFrame {

    /**
     * Creates new form Bienvenida
     */
    public Bienvenida() {
        initComponents();
    }

    FunctionGrafo funcionesGrafo = new FunctionGrafo();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CargarArchivo = new javax.swing.JButton();
        ViewGrafo = new javax.swing.JButton();
        AgregarUser = new javax.swing.JButton();
        IdentificadorComponentes = new javax.swing.JButton();
        ActulizarRepositorio = new javax.swing.JButton();
        DeleteUser = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        CargarArchivo.setBackground(new java.awt.Color(0, 0, 102));
        CargarArchivo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        CargarArchivo.setForeground(new java.awt.Color(204, 204, 255));
        CargarArchivo.setText("Cargar Archivo");
        CargarArchivo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(CargarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 190, 30));

        ViewGrafo.setBackground(new java.awt.Color(0, 0, 102));
        ViewGrafo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        ViewGrafo.setForeground(new java.awt.Color(204, 204, 255));
        ViewGrafo.setText("Visualizar grafo");
        ViewGrafo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ViewGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewGrafoActionPerformed(evt);
            }
        });
        getContentPane().add(ViewGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 190, 30));

        AgregarUser.setBackground(new java.awt.Color(0, 0, 102));
        AgregarUser.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        AgregarUser.setForeground(new java.awt.Color(204, 204, 255));
        AgregarUser.setText("Agregar usuario");
        AgregarUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AgregarUser.setMaximumSize(new java.awt.Dimension(114, 22));
        AgregarUser.setMinimumSize(new java.awt.Dimension(114, 22));
        AgregarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarUserActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 190, 30));

        IdentificadorComponentes.setBackground(new java.awt.Color(0, 0, 102));
        IdentificadorComponentes.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        IdentificadorComponentes.setForeground(new java.awt.Color(204, 204, 255));
        IdentificadorComponentes.setText("Identificador de componentes");
        IdentificadorComponentes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(IdentificadorComponentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 210, 30));

        ActulizarRepositorio.setBackground(new java.awt.Color(0, 0, 102));
        ActulizarRepositorio.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        ActulizarRepositorio.setForeground(new java.awt.Color(204, 204, 255));
        ActulizarRepositorio.setText("Actualizar repositorio");
        ActulizarRepositorio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(ActulizarRepositorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 190, 30));

        DeleteUser.setBackground(new java.awt.Color(0, 0, 102));
        DeleteUser.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        DeleteUser.setForeground(new java.awt.Color(204, 204, 255));
        DeleteUser.setText("Eliminar usuario");
        DeleteUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(DeleteUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 190, 30));

        jLabel6.setFont(new java.awt.Font("Swis721 BlkEx BT", 3, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Bienvenido");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 430, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText(" Haga Click en la opción que desee realizar!!");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sin título-3_page-0001.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(700, 442));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewGrafoActionPerformed
        // TODO add your handling code here:
        Graph dibujoGrafo = funcionesGrafo.drawGraph(grafo);
        funcionesGrafo.viewGraph(dibujoGrafo);
    }//GEN-LAST:event_ViewGrafoActionPerformed

    private void AgregarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarUserActionPerformed

    private void CargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArchivoActionPerformed
        CargarTxT archivo = new CargarTxT();
        archivo.setVisible(true);
        archivo.setLocationRelativeTo(null);
// TODO add your handling code here:
        //Grafo grafo = new Grafo();
        
//
//        JFileChooser fileChooser = new JFileChooser();
//        int resultado = fileChooser.showOpenDialog(null);
//        if (resultado == JFileChooser.APPROVE_OPTION) {
//            //try {
//            File archivo = fileChooser.getSelectedFile();
//            try {
//                grafo.cargarArchivo(archivo);
//            } catch (IOException ex) {
//                Logger.getLogger(Bienvenida.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            for (int i = 0; i < grafo.getUsuarios().size(); i++) {
//                System.out.println("Usuario: " + grafo.getUsuarios().get(i));
//                for (String conexion : grafo.getConexiones().get(i)) {
//                    System.out.println("Conexión: " + conexion);
//                }
//            }
//            } catch (FileNotFoundException ex) {
//                
//            }
//            } catch (IOException ex) {
//                
//            }
//        }
    }//GEN-LAST:event_CargarArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActulizarRepositorio;
    private javax.swing.JButton AgregarUser;
    private javax.swing.JButton CargarArchivo;
    private javax.swing.JButton DeleteUser;
    private javax.swing.JButton IdentificadorComponentes;
    private javax.swing.JButton ViewGrafo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
