/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Funciones.FunctionGrafo;
import Funciones.FunctionTXT;
import Funciones.LeerArchivo;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import proyecto1.Arista;
import proyecto1.Grafo;
import proyecto1.Vertice;
import static proyecto1.main.grafo;

/**
 *
 * @author yaxim
 */
public class CargarTxT extends javax.swing.JFrame {

    /**
     * Creates new form CargarTxT
     */
    public CargarTxT() {
        initComponents();
        this.getContentPane().setBackground(Color.cyan);
    }
    
    FunctionTXT f = new FunctionTXT();
    LeerArchivo content = new LeerArchivo();
    FunctionGrafo fGraph = new FunctionGrafo();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtPanel = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        BuscarArchivo = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        GuardarCambios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPanel.setColumns(20);
        txtPanel.setRows(5);
        jScrollPane1.setViewportView(txtPanel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 270, 180));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 56, -1, -1));

        BuscarArchivo.setBackground(new java.awt.Color(0, 0, 153));
        BuscarArchivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BuscarArchivo.setForeground(new java.awt.Color(255, 255, 255));
        BuscarArchivo.setText("Seleccionar Archivo");
        BuscarArchivo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BuscarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 170, 40));

        Exit.setBackground(new java.awt.Color(255, 255, 255));
        Exit.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Exit.setForeground(new java.awt.Color(0, 0, 0));
        Exit.setText("Salir");
        Exit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 50, -1));

        GuardarCambios.setBackground(new java.awt.Color(0, 51, 153));
        GuardarCambios.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        GuardarCambios.setForeground(new java.awt.Color(255, 255, 255));
        GuardarCambios.setText("Guardar  Cambios");
        GuardarCambios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarCambiosActionPerformed(evt);
            }
        });
        getContentPane().add(GuardarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 150, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel1.setText("Contenido del archivo seleccionado: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel2.setText("!!!RECORDATORIO!!!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        jTextArea3.setBackground(new java.awt.Color(60, 63, 65));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea3.setRows(5);
        jTextArea3.setText("Usuarios\nid_user1, @user1\nid_user2, @user2\n\nRelaciones\nid_user1, id_user2");
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 220, 130));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("El archivo a ingresar debe tener \nla siguiente estructura:");
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 220, 90));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sin título-3_page-0001.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarCambiosActionPerformed
        // TODO add your handling code here:
        //if (guardar){
        int response = JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea guardar los nuevos datos? Se reemplazara la base de datos existente en el sistema");
        if (response == JOptionPane.YES_OPTION) {
            String contenidoFile = txtPanel.getText();
            if (!f.validarTxt(contenidoFile)){
                JOptionPane.showMessageDialog(null, "El contenido del archivo no cumple con la estructura requerida\nPor favor intentelo de nuevo");
            } else{
                f.escribir_txt(contenidoFile);
                String[] usuarios = f.getUsuarios(contenidoFile);
                String[] relaciones = f.getRelaciones(contenidoFile);                
                grafo = fGraph.crearGrafo(usuarios, relaciones);  
                JOptionPane.showMessageDialog(null, "Guardado exitoso");
            }
            
            
        }
        else{
            JOptionPane.showMessageDialog(null, "No se han guardado los datos");
        }
//        } else{
//            JOptionPane.showMessageDialog(null, "Por favor ingrese un archivo con la estructura requerida\npara actualizar la base de datos del sistema");
//        }   
        
    }//GEN-LAST:event_GuardarCambiosActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void BuscarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarArchivoActionPerformed
        // TODO add your handling code here:
        
         Grafo grafo = new Grafo();
        

        JFileChooser fileChooser = new JFileChooser();
        int resultado = fileChooser.showOpenDialog(null);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            //try {
            File archivo = fileChooser.getSelectedFile();
            try {
                
                String infoGrafo = grafo.cargarArchivo(archivo);
                FunctionTXT use = new FunctionTXT();
                String[] users = use.getUsuarios(infoGrafo);
                String[] relaciones = use.getRelaciones(infoGrafo);
//                txtPanel.append("Usuarios");
//                for (int i = 1; i < users.length; i++) {
//                    String[] info = users[i].trim().split(",");
//                    String username = info[1].trim();
//                    String id = info[0].trim();
//                    String usuarioTxt = id + ", " + username;
//                    txtPanel.append(usuarioTxt);                
//                }
                //txt.append("Relaciones");
//                tring infoGrafo = grafo.cargarArchivo(archivo);
//                FunctionTXT use = new FunctionTXT();
//                String[] users = use.getUsuarios(infoGrafo);
//                String[] relaciones = use.getRelaciones(infoGrafo);
                txtPanel.append("Usuarios\n");
                for (int i = 1; i < users.length; i++) {
                    String[] info = users[i].trim().split(",");
                    String username = info[1].trim();
                    String id = info[0].trim();
                    String usuarioTxt = id + ", " + username + "\n";
                    txtPanel.append(usuarioTxt);                
                }
                txtPanel.append("Relaciones\n");
                for (int j = 1; j < relaciones.length; j++) {
                        String[] relationships = relaciones[j].trim().split(",");
                        int id1 = Integer.parseInt(relationships[0].trim());
                        int id2 = Integer.parseInt(relationships[1].trim());
                        String relacionTxt = id1 + ", " + id2+ "\n";
                        txtPanel.append(relacionTxt);      
                    }
                
            } catch (IOException ex) {
                //Logger.getLogger(Bienvenida.class.getName()).log(Level.ERROR, null, ex);
            }
            
                
        }
//            List<String> conexionTxt = new ArrayList<>();
//            for (int i = 0; i < grafo.getUsuarios().size(); i++) {
//                Vertice usuario = grafo.getUsuarios().get(i);
//                //System.out.println("Usuario: " + grafo.getUsuarios().get(i));
//                String usuarioTxt = usuario.getId() + ", " + usuario.getNombre();
//                txt.append(usuarioTxt);
//                for (Arista conexion : usuario.getConexions()) {
//                    conexionTxt.add(conexion.getStart().getId() + ", " + conexion.getEnd().getId());
//                    //System.out.println("Conexión: " + conexion.getStart().getNombre() + " --> " + conexion.getEnd().getNombre());
//                    
//                }
//            }
//            } catch (FileNotFoundException ex) {
//                
//            }
//            } catch (IOException ex) {
//                
//            }
        //}
    }//GEN-LAST:event_BuscarArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargarTxT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargarTxT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargarTxT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargarTxT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargarTxT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarArchivo;
    private javax.swing.JButton Exit;
    private javax.swing.JButton GuardarCambios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea txtPanel;
    // End of variables declaration//GEN-END:variables
}
