/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Funciones.FunctionGrafo;
import Funciones.FunctionTXT;
import Funciones.LeerArchivo;
import javax.swing.JOptionPane;
import static proyecto1.main.grafo;

/**
 *
 * @author yaxim
 */
public class EliminarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form EliminarUsuario
     */
    public EliminarUsuario() {
        initComponents();
        
        InicializarComboBox();
    }
    
    LeerArchivo f = new LeerArchivo();
    FunctionTXT content = new FunctionTXT();
    FunctionGrafo fGraph = new FunctionGrafo();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UserEliminado = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        Eliminar = new javax.swing.JButton();
        Exit1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        UserEliminado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UserEliminado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UserEliminado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserEliminadoActionPerformed(evt);
            }
        });
        getContentPane().add(UserEliminado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 240, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario a eliminar : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, 30));

        Eliminar.setBackground(new java.awt.Color(255, 102, 102));
        Eliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(0, 0, 0));
        Eliminar.setText("Eliminar");
        Eliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 150, 30));

        Exit1.setBackground(new java.awt.Color(255, 255, 255));
        Exit1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Exit1.setForeground(new java.awt.Color(0, 0, 0));
        Exit1.setText("Salir");
        Exit1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit1ActionPerformed(evt);
            }
        });
        getContentPane().add(Exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 50, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Sin título-3_page-0001.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
String infoGrafo = f.leertxt("test\\proyecto.txt");
        String[] users = content.getUsuarios(infoGrafo);
        String[] relaciones = content.getRelaciones(infoGrafo);
        Object selectedItem1 = UserEliminado.getSelectedItem(); 
        int userIdEliminar = getUserIdByName(users, selectedItem1.toString());
        int response = JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea eliminar el usuario? Se eliminarán las relaciones existente en el sistema");
        if (response == JOptionPane.YES_OPTION) {
            
            String contenidoFile = "Usuarios\n";  
            for (int i = 1; i < users.length; i++) {
                String[] info = users[i].trim().split(",");
                String username = info[1].trim();
                //String id = info[0].trim();
                if (!username.equalsIgnoreCase(selectedItem1.toString())) {
                    contenidoFile += users[i] + "\n";  
                }                         
            }
            contenidoFile += "Relaciones\n";
            for (int j = 1; j < relaciones.length; j++) {
                String[] relationships = relaciones[j].trim().split(",");
                int id1 = Integer.parseInt(relationships[0].trim());
                int id2 = Integer.parseInt(relationships[1].trim());
                if (id1 != userIdEliminar && id2 != userIdEliminar) {
                    contenidoFile += relaciones[j]+ "\n";   
                }               
            }
            
            content.escribir_txt(contenidoFile);
                       
            String[] usuariosActualizados = content.getUsuarios(contenidoFile);
            String[] relacionesActualizadas = content.getRelaciones(contenidoFile);                
            grafo = fGraph.crearGrafo(usuariosActualizados, relacionesActualizadas);  
            JOptionPane.showMessageDialog(null, "Usuario eliminado exitosamente");
        }

    }//GEN-LAST:event_EliminarActionPerformed

    private void UserEliminadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserEliminadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserEliminadoActionPerformed

    private void Exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Exit1ActionPerformed

    
    private void InicializarComboBox() {
        
        String infoGrafo = f.leertxt("test\\proyecto.txt");
        String[] users = content.getUsuarios(infoGrafo);
        String[] relaciones = content.getRelaciones(infoGrafo);
        for (int i = 1; i < users.length; i++) {
            String[] info = users[i].trim().split(",");
            String username = info[1].trim();
            String id = info[0].trim();  
            UserEliminado.addItem(username);
         }
    }
    
    private int getUserIdByName(String[] users, String selectedItemName) {
        for (int i = 1; i < users.length; i++) {
            String[] info = users[i].trim().split(",");
            String username = info[1].trim();
            String id = info[0].trim();  
            if (username.equalsIgnoreCase(selectedItemName)) {
                return Integer.parseInt(id);
            }
        }
        return -1;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Exit1;
    private javax.swing.JComboBox<String> UserEliminado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
