/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author yaxim
 */
public class FunctionalRequirements_old extends javax.swing.JFrame {

    /**
     * Creates new form FunctionalRequirements
     */
    public FunctionalRequirements_old() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Bienvenida = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CargarArchivo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        AgregarUser = new javax.swing.JButton();
        DeleteUser = new javax.swing.JButton();
        ViewGrafo = new javax.swing.JButton();
        IdentificadorComponentes = new javax.swing.JButton();
        ActulizarRepositorio = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        Bienvenida.setColumns(20);
        Bienvenida.setRows(5);
        Bienvenida.setText("Bienvenidos");
        jScrollPane1.setViewportView(Bienvenida);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/OLas.jpeg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/Olas 1.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setFont(new java.awt.Font("Stencil", 3, 36)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Swis721 BlkEx BT", 3, 48)); // NOI18N
        jLabel6.setText("Bienvenido");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 430, -1));

        CargarArchivo.setText("Cargar archivo");
        CargarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArchivoActionPerformed(evt);
            }
        });
        jPanel1.add(CargarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 180, 30));

        jLabel7.setText(" Haga Click en la opción que desee realizar!!");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        AgregarUser.setText("Agregar usuario");
        AgregarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarUserActionPerformed(evt);
            }
        });
        jPanel1.add(AgregarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 180, 30));

        DeleteUser.setText("Eliminar usuario");
        jPanel1.add(DeleteUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 180, 30));

        ViewGrafo.setText("Visualizar grafo");
        ViewGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewGrafoActionPerformed(evt);
            }
        });
        jPanel1.add(ViewGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 180, 30));

        IdentificadorComponentes.setText("Identificador de componentes");
        jPanel1.add(IdentificadorComponentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 200, 30));

        ActulizarRepositorio.setText("Actualizar repositorio");
        jPanel1.add(ActulizarRepositorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 180, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/newpackage/newpackage/Sin título-3_page-0001.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 720, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 20, 710, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewGrafoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewGrafoActionPerformed

    private void AgregarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarUserActionPerformed

    private void CargarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CargarArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FunctionalRequirements_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FunctionalRequirements_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FunctionalRequirements_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FunctionalRequirements_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FunctionalRequirements_old().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActulizarRepositorio;
    private javax.swing.JButton AgregarUser;
    private javax.swing.JTextArea Bienvenida;
    private javax.swing.JButton CargarArchivo;
    private javax.swing.JButton DeleteUser;
    private javax.swing.JButton IdentificadorComponentes;
    private javax.swing.JButton ViewGrafo;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
